# ========================
# Server
# ========================
server.port=8080

# ========================
# DataSource (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/equipment_management_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=equipment_admin
spring.datasource.password=equipment_pass

# ========================
# JPA / Hibernate
# ========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# Jackson
# ========================
spring.jackson.serialization.write-dates-as-timestamps=false
